# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            катя иуда
tagline:          'портфолио'
url: "https://eyumarchenko.github.io"
baseurl: "/love_for_judas"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/eyumarchenko/love_for_judas

permalink:        /:title/

lang: ru
locale: ru_RU